# Generated by Django 5.2.16 on 2026-08-03 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'nombre',
                    models.CharField(
                        max_length=200,
                    ),
                ),
                (
                    'descripcion',
                    models.TextField(
                        blank=True,
                    ),
                ),
                (
                    'archivo',
                    models.FileField(
                        upload_to='portafolio/documentos/',
                    ),
                ),
                (
                    'creado_en',
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': [
                    '-creado_en',
                ],
            },
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'nombre',
                    models.CharField(
                        max_length=150,
                    ),
                ),
                (
                    'clave',
                    models.SlugField(
                        unique=True,
                    ),
                ),
                (
                    'descripcion',
                    models.TextField(
                        blank=True,
                    ),
                ),
                (
                    'instrucciones',
                    models.TextField(
                        blank=True,
                    ),
                ),
                (
                    'activo',
                    models.BooleanField(
                        default=True,
                    ),
                ),
                (
                    'creado_en',
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
                'ordering': [
                    'nombre',
                ],
            },
        ),
        migrations.CreateModel(
            name='PlantillaPDF',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'nombre',
                    models.CharField(
                        max_length=200,
                    ),
                ),
                (
                    'descripcion',
                    models.TextField(
                        blank=True,
                    ),
                ),
                (
                    'archivo',
                    models.FileField(
                        upload_to='portafolio/plantillas_pdf/',
                    ),
                ),
                (
                    'activa',
                    models.BooleanField(
                        default=True,
                    ),
                ),
                (
                    'creado_en',
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Plantilla PDF',
                'verbose_name_plural': 'Plantillas PDF',
                'ordering': [
                    'nombre',
                ],
            },
        ),
        migrations.CreateModel(
            name='RecursoCompartido',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'nombre',
                    models.CharField(
                        max_length=200,
                    ),
                ),
                (
                    'tipo',
                    models.CharField(
                        blank=True,
                        max_length=100,
                    ),
                ),
                (
                    'descripcion',
                    models.TextField(
                        blank=True,
                    ),
                ),
                (
                    'archivo',
                    models.FileField(
                        upload_to='portafolio/recursos/',
                    ),
                ),
                (
                    'activo',
                    models.BooleanField(
                        default=True,
                    ),
                ),
                (
                    'creado_en',
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Recurso compartido',
                'verbose_name_plural': 'Recursos compartidos',
                'ordering': [
                    'nombre',
                ],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'nombre',
                    models.CharField(
                        max_length=200,
                    ),
                ),
                (
                    'clave',
                    models.SlugField(
                        unique=True,
                    ),
                ),
                (
                    'descripcion',
                    models.TextField(
                        blank=True,
                    ),
                ),
                (
                    'activo',
                    models.BooleanField(
                        default=True,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': [
                    'nombre',
                ],
            },
        ),
        migrations.CreateModel(
            name='PreguntaInstrumento',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'orden',
                    models.PositiveIntegerField(
                        default=0,
                    ),
                ),
                (
                    'texto',
                    models.TextField(),
                ),
                (
                    'clave',
                    models.CharField(
                        blank=True,
                        max_length=50,
                    ),
                ),
                (
                    'tipo_respuesta',
                    models.CharField(
                        choices=[
                            (
                                'opcion_unica',
                                'Opción única',
                            ),
                            (
                                'opcion_multiple',
                                'Opción múltiple',
                            ),
                            (
                                'escala',
                                'Escala Likert',
                            ),
                            (
                                'si_no',
                                'Sí / No',
                            ),
                            (
                                'texto_libre',
                                'Texto libre',
                            ),
                        ],
                        default='opcion_unica',
                        max_length=20,
                    ),
                ),
                (
                    'opciones',
                    models.JSONField(
                        blank=True,
                        help_text='Lista de objetos {valor, etiqueta}.',
                        null=True,
                    ),
                ),
                (
                    'requerida',
                    models.BooleanField(
                        default=True,
                    ),
                ),
                (
                    'instrumento',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='preguntas',
                        to='portafolio.instrumento',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Pregunta de instrumento',
                'verbose_name_plural': 'Preguntas de instrumentos',
                'ordering': [
                    'instrumento',
                    'orden',
                    'id',
                ],
            },
        ),
    ]