# Generated by Django 5.2.16 on 2026-08-03 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def crear_categorias_iniciales(apps, schema_editor):
    CategoriaDocumento = apps.get_model(
        'portafolio',
        'CategoriaDocumento',
    )

    for nombre in (
        'Instrumento',
        'Plantilla PDF',
        'Reporte',
        'Evidencia',
        'Manual',
        'Documento Institucional',
        'Recurso Compartido',
        'Multimedia',
        'Otro',
    ):
        CategoriaDocumento.objects.get_or_create(
            nombre=nombre
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            'portafolio',
            '0001_initial',
        ),
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'nombre',
                    models.CharField(
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    'descripcion',
                    models.TextField(
                        blank=True,
                    ),
                ),
                (
                    'activa',
                    models.BooleanField(
                        default=True,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Categoría de documento',
                'verbose_name_plural': (
                    'Categorías de documentos'
                ),
                'ordering': [
                    'nombre',
                ],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='cargado_por',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='documentos_portafolio',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='documento',
            name='estado',
            field=models.CharField(
                choices=[
                    (
                        'activo',
                        'Activo',
                    ),
                    (
                        'inactivo',
                        'Inactivo',
                    ),
                ],
                default='activo',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='documento',
            name='observaciones',
            field=models.TextField(
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_archivo',
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='documento',
            name='version',
            field=models.CharField(
                default='1.0',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='documento_origen',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='instrumentos_origen',
                to='portafolio.documento',
            ),
        ),
        migrations.AddField(
            model_name='plantillapdf',
            name='documento_origen',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='plantillas_pdf',
                to='portafolio.documento',
            ),
        ),
        migrations.AddField(
            model_name='recursocompartido',
            name='documento_origen',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='recursos_compartidos',
                to='portafolio.documento',
            ),
        ),
        migrations.AddField(
            model_name='documento',
            name='categoria',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='documentos',
                to='portafolio.categoriadocumento',
            ),
        ),
        migrations.RunPython(
            crear_categorias_iniciales,
            migrations.RunPython.noop,
        ),
    ]