# Generated by Django 5.2.16 on 2026-08-05 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'portafolio',
            '0004_cargar_plantilla_entrevista_1a1',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='huella_contenido',
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='metadatos',
            field=models.JSONField(
                blank=True,
                default=dict,
            ),
        ),
        migrations.CreateModel(
            name='CalculadoraInstrumento',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'clave',
                    models.SlugField(
                        max_length=80,
                    ),
                ),
                (
                    'version_regla',
                    models.CharField(
                        max_length=30,
                    ),
                ),
                (
                    'estado',
                    models.CharField(
                        choices=[
                            (
                                'activa',
                                'Activa',
                            ),
                            (
                                'orientativa',
                                'Orientativa',
                            ),
                            (
                                'bloqueada',
                                'Bloqueada',
                            ),
                            (
                                'no_diagnostica',
                                'No diagnóstica',
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'definicion',
                    models.JSONField(
                        default=dict,
                    ),
                ),
                (
                    'huella_contenido',
                    models.CharField(
                        max_length=64,
                    ),
                ),
                (
                    'creada_en',
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    'instrumento',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='calculadoras',
                        to='portafolio.instrumento',
                    ),
                ),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(
                        fields=(
                            'instrumento',
                            'clave',
                            'version_regla',
                        ),
                        name='calculadora_unica_por_version',
                    ),
                ],
            },
        ),
    ]