# Generated by Django 5.2.16 on 2026-08-05 04:18

import django.db.models.deletion
from django.db import migrations, models


def copiar_importaciones(apps, schema_editor):
    Instrumento = apps.get_model(
        'portafolio',
        'Instrumento',
    )
    Importacion = apps.get_model(
        'portafolio',
        'ImportacionInstrumento',
    )

    for instrumento in Instrumento.objects.all().iterator():
        if not instrumento.documento_origen_id:
            continue

        Importacion.objects.update_or_create(
            instrumento_id=instrumento.id,
            defaults={
                'documento_id': instrumento.documento_origen_id,
                'huella_contenido': (
                    instrumento.documento_origen.huella_contenido
                    if instrumento.documento_origen_id
                    else ''
                ),
                'metadatos': instrumento.metadatos or {},
            },
        )


def restaurar_importaciones(apps, schema_editor):
    Instrumento = apps.get_model(
        'portafolio',
        'Instrumento',
    )
    Importacion = apps.get_model(
        'portafolio',
        'ImportacionInstrumento',
    )

    for registro in Importacion.objects.all().iterator():
        Instrumento.objects.filter(
            pk=registro.instrumento_id
        ).update(
            metadatos=registro.metadatos
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            'portafolio',
            '0005_documento_huella_contenido_instrumento_metadatos_and_more',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionInstrumento',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'huella_contenido',
                    models.CharField(
                        db_index=True,
                        max_length=64,
                    ),
                ),
                (
                    'metadatos',
                    models.JSONField(
                        blank=True,
                        default=dict,
                    ),
                ),
                (
                    'creada_en',
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    'documento',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='importaciones_instrumento',
                        to='portafolio.documento',
                    ),
                ),
                (
                    'instrumento',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='importacion',
                        to='portafolio.instrumento',
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            copiar_importaciones,
            restaurar_importaciones,
        ),
        migrations.RemoveField(
            model_name='documento',
            name='huella_contenido',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='metadatos',
        ),
    ]