# Generated by Django 6.0.6 on 2026-07-27 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion_objeto', models.CharField(blank=True, max_length=255)),
                ('accion', models.CharField(choices=[('creo', 'Creó'), ('modifico', 'Modificó'), ('sello', 'Selló'), ('ajusto', 'Ajustó'), ('importo', 'Importó / sincronizó'), ('elimino', 'Eliminó')], max_length=20)),
                ('campo', models.CharField(blank=True, max_length=60)),
                ('valor_anterior', models.CharField(blank=True, max_length=255)),
                ('valor_nuevo', models.CharField(blank=True, max_length=255)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Bitácora de auditoría',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='core_regist_fecha_bfe2ba_idx'), models.Index(fields=['content_type', 'object_id'], name='core_regist_content_3b3fcb_idx')],
            },
        ),
    ]
