# Generated by Django 6.0.6 on 2026-07-27 05:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_categoriaegreso_conceptoingreso_ingreso_monto_pagado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ajuste',
            name='monto_anterior',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='ajuste',
            name='monto_nuevo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='ajuste',
            name='usuario',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_registrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
