# Generated by Django 6.0.6 on 2026-07-27 05:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0008_ajuste_monto_anterior_ajuste_monto_nuevo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaNominaSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(max_length=150)),
                ('tipo_persona', models.CharField(choices=[('terapeuta', 'Terapeuta'), ('administrativo', 'Administrativo')], default='terapeuta', max_length=20)),
                ('concepto', models.CharField(default='Pago a terapeuta', max_length=150)),
                ('citas_atendidas', models.PositiveIntegerField(default=0)),
                ('ingreso_generado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pago_base', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('vale_gasolina', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Vale de gasolina / bono')),
                ('extras', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Bono extra / otros autorizados')),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('estatus_pago', models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente de pago')], default='pendiente', max_length=10)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('referencia_corte', models.CharField(blank=True, max_length=60)),
                ('detalle_json', models.JSONField(blank=True, default=list)),
                ('sellada', models.BooleanField(default=False)),
                ('sellada_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Línea de nómina',
                'verbose_name_plural': 'Líneas de nómina',
                'ordering': ['persona'],
            },
        ),
        migrations.AddField(
            model_name='egreso',
            name='linea_nomina',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos', to='finanzas.lineanominasemanal'),
        ),
        migrations.CreateModel(
            name='NominaSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('administrativa', 'Administrativa')], default='semanal', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('sellada', 'Sellada')], default='borrador', max_length=10)),
                ('sellada_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario_genera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominas_generadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nómina semanal',
                'verbose_name_plural': 'Nóminas semanales',
                'ordering': ['-fecha_fin', 'tipo'],
                'unique_together': {('tipo', 'fecha_inicio', 'fecha_fin')},
            },
        ),
        migrations.AddField(
            model_name='lineanominasemanal',
            name='nomina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='finanzas.nominasemanal'),
        ),
        migrations.AlterUniqueTogether(
            name='lineanominasemanal',
            unique_together={('nomina', 'persona')},
        ),
    ]
