# Generated by Django 6.0.6 on 2026-07-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0009_lineanominasemanal_egreso_linea_nomina_nominasemanal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineanominasemanal',
            name='montos_editados',
            field=models.BooleanField(default=False),
        ),
    ]
