# Generated by Django 6.0.6 on 2026-07-27 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0010_lineanominasemanal_montos_editados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nominaacademia',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('sellada', 'Sellada')], default='borrador', max_length=10),
        ),
        migrations.AddField(
            model_name='nominaacademia',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nominaacademia',
            name='sellada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nominaacademia',
            name='usuario_genera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominas_academia_generadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
