# Generated by Django 5.2.10 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "certificacion_intera",
            "0001_grupo_certificacion",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Escuela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200,
                    ),
                ),
                (
                    "nivel_educativo",
                    models.CharField(
                        blank=True,
                        max_length=100,
                    ),
                ),
                (
                    "director",
                    models.CharField(
                        max_length=150,
                    ),
                ),
                (
                    "cantidad_total_alumnos",
                    models.PositiveIntegerField(),
                ),
                (
                    "contacto",
                    models.CharField(
                        blank=True,
                        max_length=150,
                    ),
                ),
                (
                    "correo",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True,
                        max_length=30,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        max_length=100,
                    ),
                ),
                (
                    "municipio",
                    models.CharField(
                        max_length=100,
                    ),
                ),
                (
                    "direccion",
                    models.TextField(
                        blank=True,
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Escuela",
                "verbose_name_plural": "Escuelas",
                "ordering": ["nombre"],
            },
        ),
    ]