# Generated by Django 5.2.16 on 2026-08-03 01:55

import django.db.models.deletion
from django.db import migrations, models


def mover_instrumentos_a_portafolio(apps, schema_editor):
    InstrumentoAnterior = apps.get_model(
        "certificacion_intera",
        "Instrumento",
    )
    PreguntaAnterior = apps.get_model(
        "certificacion_intera",
        "PreguntaInstrumento",
    )
    Instrumento = apps.get_model(
        "portafolio",
        "Instrumento",
    )
    Pregunta = apps.get_model(
        "portafolio",
        "PreguntaInstrumento",
    )

    for origen in InstrumentoAnterior.objects.all():
        Instrumento.objects.update_or_create(
            id=origen.id,
            defaults={
                "nombre": origen.nombre,
                "clave": origen.clave,
                "descripcion": origen.descripcion,
                "instrucciones": origen.instrucciones,
                "activo": origen.activo,
                "creado_en": origen.creado_en,
            },
        )

    for origen in PreguntaAnterior.objects.all():
        Pregunta.objects.update_or_create(
            id=origen.id,
            defaults={
                "instrumento_id": origen.instrumento_id,
                "orden": origen.orden,
                "texto": origen.texto,
                "clave": origen.clave,
                "tipo_respuesta": origen.tipo_respuesta,
                "opciones": origen.opciones,
                "requerida": origen.requerida,
            },
        )


def reverso_mover_instrumentos(apps, schema_editor):
    # La reversión de estructura conserva los registros históricos existentes.
    pass


class Migration(migrations.Migration):

    dependencies = [
        (
            "certificacion_intera",
            "0004_procesocertificacion_ciclo_escolar",
        ),
        (
            "portafolio",
            "0001_initial",
        ),
    ]

    operations = [
        migrations.RunPython(
            mover_instrumentos_a_portafolio,
            reverso_mover_instrumentos,
        ),
        migrations.AlterField(
            model_name="aplicacioninstrumento",
            name="instrumento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aplicaciones_intera",
                to="portafolio.instrumento",
            ),
        ),
        migrations.RemoveField(
            model_name="preguntainstrumento",
            name="instrumento",
        ),
        migrations.AlterField(
            model_name="configuracioninstrumento",
            name="instrumento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="configuraciones_intera",
                to="portafolio.instrumento",
            ),
        ),
        migrations.AlterField(
            model_name="respuestainstrumento",
            name="pregunta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respuestas_intera",
                to="portafolio.preguntainstrumento",
            ),
        ),
        migrations.AlterModelOptions(
            name="aplicacioninstrumento",
            options={
                "ordering": ["-creado_en"],
            },
        ),
        migrations.AlterModelOptions(
            name="canalizacion",
            options={},
        ),
        migrations.AlterModelOptions(
            name="consejeria",
            options={},
        ),
        migrations.AlterModelOptions(
            name="entrevistaseguimiento",
            options={},
        ),
        migrations.AlterModelOptions(
            name="participante",
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.AlterModelOptions(
            name="respuestainstrumento",
            options={
                "ordering": ["pregunta__orden"],
            },
        ),
        migrations.DeleteModel(
            name="Instrumento",
        ),
        migrations.DeleteModel(
            name="PreguntaInstrumento",
        ),
    ]