# Generated by Django 5.2.16 on 2026-08-03 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'certificacion_intera',
            '0006_aplicacionpublica_bitacoraproceso_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacioninstrumento',
            name='aplicacion_publica',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='aplicaciones_individuales',
                to='certificacion_intera.aplicacionpublica',
            ),
        ),
    ]