# Generated by Django 5.2.16 on 2026-08-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "certificacion_intera",
            "0007_aplicacioninstrumento_aplicacion_publica",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="participante",
            name="fecha_nacimiento",
            field=models.DateField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="participante",
            name="sexo",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "femenino",
                        "Femenino",
                    ),
                    (
                        "masculino",
                        "Masculino",
                    ),
                    (
                        "otro",
                        "Otro",
                    ),
                    (
                        "no_especificado",
                        "Prefiero no especificar",
                    ),
                ],
                max_length=15,
            ),
        ),
    ]