# Generated by Django 5.2.16 on 2026-08-03 18:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "certificacion_intera",
            "0008_participante_fecha_nacimiento_participante_sexo",
        ),
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL,
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="canalizacion",
            options={
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.AddField(
            model_name="canalizacion",
            name="actualizada_en",
            field=models.DateTimeField(
                auto_now=True,
            ),
        ),
        migrations.AddField(
            model_name="canalizacion",
            name="comentarios_recepcion",
            field=models.TextField(
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="canalizacion",
            name="error_sincronizacion",
            field=models.TextField(
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="canalizacion",
            name="estado_clinico",
            field=models.CharField(
                choices=[
                    (
                        "sin_respuesta",
                        "Sin respuesta",
                    ),
                    (
                        "recibida",
                        "Recibida",
                    ),
                    (
                        "cita_programada",
                        "Cita programada",
                    ),
                    (
                        "atendida",
                        "Paciente atendido",
                    ),
                    (
                        "cerrada",
                        "Cerrada",
                    ),
                ],
                default="sin_respuesta",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="canalizacion",
            name="estado_envio",
            field=models.CharField(
                choices=[
                    (
                        "pendiente",
                        "Pendiente de envío",
                    ),
                    (
                        "enviada",
                        "Enviada",
                    ),
                    (
                        "confirmada",
                        "Confirmada",
                    ),
                    (
                        "error",
                        "Error de sincronización",
                    ),
                ],
                default="pendiente",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="canalizacion",
            name="fecha_cierre",
            field=models.DateTimeField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="canalizacion",
            name="fecha_envio",
            field=models.DateTimeField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="canalizacion",
            name="fecha_respuesta",
            field=models.DateTimeField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="canalizacion",
            name="prioridad",
            field=models.CharField(
                choices=[
                    (
                        "baja",
                        "Baja",
                    ),
                    (
                        "media",
                        "Media",
                    ),
                    (
                        "alta",
                        "Alta",
                    ),
                    (
                        "urgente",
                        "Urgente",
                    ),
                ],
                default="media",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="canalizacion",
            name="registrada_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="canalizaciones_registradas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="canalizacion",
            name="remoto_id",
            field=models.CharField(
                blank=True,
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="canalizacion",
            name="sincronizado_en",
            field=models.DateTimeField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="canalizacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    (
                        "ordinaria",
                        "Ordinaria",
                    ),
                    (
                        "voluntaria",
                        "Voluntaria",
                    ),
                    (
                        "emergencia",
                        "Emergencia",
                    ),
                ],
                default="ordinaria",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="canalizacion",
            name="estado",
            field=models.CharField(
                choices=[
                    (
                        "registrada",
                        "Registrada",
                    ),
                    (
                        "pendiente_envio",
                        "Pendiente de envío",
                    ),
                    (
                        "enviada",
                        "Enviada a recepción",
                    ),
                    (
                        "confirmada",
                        "Recepción confirmada",
                    ),
                    (
                        "cita_programada",
                        "Cita programada",
                    ),
                    (
                        "atendida",
                        "Paciente atendido",
                    ),
                    (
                        "cerrada",
                        "Cerrada",
                    ),
                    (
                        "cancelada",
                        "Cancelada",
                    ),
                ],
                default="pendiente_envio",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="canalizacion",
            name="fecha",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                verbose_name="Fecha de solicitud",
            ),
        ),
        migrations.RunSQL(
            (
                "UPDATE certificacion_intera_canalizacion "
                "SET estado = CASE estado "
                "WHEN 'pendiente' THEN 'pendiente_envio' "
                "WHEN 'en_proceso' THEN 'enviada' "
                "ELSE estado END"
            ),
            (
                "UPDATE certificacion_intera_canalizacion "
                "SET estado = CASE estado "
                "WHEN 'pendiente_envio' THEN 'pendiente' "
                "WHEN 'enviada' THEN 'en_proceso' "
                "ELSE estado END"
            ),
        ),
        migrations.AddConstraint(
            model_name="canalizacion",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "estado__in",
                        [
                            "registrada",
                            "pendiente_envio",
                            "enviada",
                            "confirmada",
                            "cita_programada",
                            "atendida",
                        ],
                    )
                ),
                fields=(
                    "participante",
                ),
                name="canalizacion_activa_unica_por_participante",
            ),
        ),
    ]