# Generated by Django 5.2.16 on 2026-08-03 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'certificacion_intera',
            '0009_alter_canalizacion_options_and_more',
        ),
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL,
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAtencion',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'estado',
                    models.CharField(
                        choices=[
                            (
                                'pendiente_envio',
                                'Pendiente de envío',
                            ),
                            (
                                'enviada',
                                'Enviada',
                            ),
                            (
                                'recibida',
                                'Recibida',
                            ),
                            (
                                'aceptada',
                                'Aceptada',
                            ),
                            (
                                'paciente_registrado',
                                'Paciente registrado',
                            ),
                            (
                                'cita_programada',
                                'Cita programada',
                            ),
                            (
                                'finalizada',
                                'Finalizada',
                            ),
                            (
                                'cancelada',
                                'Cancelada',
                            ),
                            (
                                'error',
                                'Error de sincronización',
                            ),
                        ],
                        default='pendiente_envio',
                        max_length=22,
                    ),
                ),
                (
                    'creado_en',
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    'actualizado_en',
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
                (
                    'fecha_envio',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    'fecha_respuesta',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    'fecha_programacion',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    'fecha_cierre',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    'observaciones',
                    models.TextField(
                        blank=True,
                    ),
                ),
                (
                    'comentarios_recepcion',
                    models.TextField(
                        blank=True,
                    ),
                ),
                (
                    'remoto_id',
                    models.CharField(
                        blank=True,
                        max_length=100,
                    ),
                ),
                (
                    'estado_sincronizacion',
                    models.CharField(
                        choices=[
                            (
                                'pendiente',
                                'Sincronización pendiente',
                            ),
                            (
                                'sincronizada',
                                'Sincronizada',
                            ),
                            (
                                'error',
                                'Error',
                            ),
                        ],
                        default='pendiente',
                        max_length=15,
                    ),
                ),
                (
                    'sincronizado_en',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    'ultimo_error',
                    models.TextField(
                        blank=True,
                    ),
                ),
                (
                    'canalizacion',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='solicitud_atencion',
                        to='certificacion_intera.canalizacion',
                    ),
                ),
                (
                    'creada_por',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='solicitudes_atencion',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Solicitud de Atención',
                'verbose_name_plural': 'Solicitudes de Atención',
                'ordering': ['-creado_en'],
            },
        ),
    ]