# Generated by Django 5.2.16 on 2026-08-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'certificacion_intera',
            '0013_entrevistaunoauno_historialentrevistaunoauno_and_more',
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracioninstrumento',
            options={
                'ordering': (
                    'orden',
                    'id',
                ),
                'verbose_name': 'Configuración de instrumento',
                'verbose_name_plural': 'Configuraciones de instrumentos',
            },
        ),
        migrations.AddField(
            model_name='configuracioninstrumento',
            name='orden',
            field=models.PositiveIntegerField(
                default=0,
            ),
        ),
    ]