# Generated by Django 5.2.16 on 2026-08-05 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'certificacion_intera',
            '0014_alter_configuracioninstrumento_options_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacioninstrumento',
            name='iniciada_en',
            field=models.DateTimeField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='aplicacionpublica',
            name='proceso',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='aplicacion_publica_general',
                to='certificacion_intera.procesocertificacion',
            ),
        ),
        migrations.AddField(
            model_name='participante',
            name='privacidad_aceptada_en',
            field=models.DateTimeField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='participante',
            name='privacidad_version',
            field=models.CharField(
                blank=True,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='aplicacionpublica',
            name='configuracion',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='aplicacion_publica',
                to='certificacion_intera.configuracioninstrumento',
            ),
        ),
        migrations.AddConstraint(
            model_name='aplicacionpublica',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        'configuracion__isnull',
                        False,
                    ),
                    (
                        'proceso__isnull',
                        False,
                    ),
                    _connector='OR',
                ),
                name='aplicacion_publica_con_origen',
            ),
        ),
    ]