# Generated by Django 5.2.16 on 2026-08-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion_intera', '0015_aplicacioninstrumento_iniciada_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacioninstrumento',
            name='revision_calculadora',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
