# Generated by Django 5.2.10 on 2026-08-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion_intera', '0016_aplicacioninstrumento_revision_calculadora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacioninstrumento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('respondida', 'Concluida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15),
        ),
    ]
