"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-uhy@c@kht^qvc838(p9txqnxf^fk)a-ne3q0*f-=6bw+a!8bh4',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get(
    'DEBUG',
    'False' if os.environ.get('RAILWAY_ENVIRONMENT') else 'True',
).lower() in {'1', 'true', 'yes', 'on'}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        'ALLOWED_HOSTS',
        'localhost,127.0.0.1,.railway.app,.up.railway.app',
    ).split(',')
    if host.strip()
]

RAILWAY_PUBLIC_DOMAIN = os.environ.get('RAILWAY_PUBLIC_DOMAIN')
if RAILWAY_PUBLIC_DOMAIN:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'CSRF_TRUSTED_ORIGINS',
        'https://*.railway.app,https://*.up.railway.app',
    ).split(',')
    if origin.strip()
]
if RAILWAY_PUBLIC_DOMAIN:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RAILWAY_PUBLIC_DOMAIN}')


# Application definition

INSTALLED_APPS = [
     # Núcleo del portal: acceso de usuarios, autenticación y permisos.
    'apps.core',
    # Módulo de Finanzas: ingresos, egresos, nómina, donativos y reportes.
    'apps.finanzas',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Evita que "atrás" del navegador muestre páginas protegidas ya
    # renderizadas después de cerrar sesión (ver apps/core/middleware.py).
    'apps.core.middleware.NoCacheMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#Pendiente por configurar el correo institucional para enviar correos de recuperación de contraseña.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'tu-correo-institucional@ejemplo.com'
EMAIL_HOST_PASSWORD = 'tu-app-password' # Nota: se genera en la seguridad de Google#

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# 'UTC' (no 'America/Mexico_City') hacía que la Bitácora comparara y
# mostrara fechas en huso UTC: un movimiento de la tarde/noche en México
# (UTC-6) caía en el día SIGUIENTE al filtrar o mostrar `RegistroAuditoria.
# fecha` (DateTimeField), aunque para quien lo capturó fuera claramente
# "hoy". Con USE_TZ=True, Django sigue guardando en UTC internamente; esto
# solo cambia el huso usado para mostrar y para los filtros __date.
TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = os.environ.get(
    'SECURE_SSL_REDIRECT',
    str(not DEBUG),
).lower() in {'1', 'true', 'yes', 'on'}
SECURE_HSTS_SECONDS = int(os.environ.get(
    'SECURE_HSTS_SECONDS',
    '0' if DEBUG else '3600',
))
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# Cierre de sesión por inactividad: SESSION_SAVE_EVERY_REQUEST hace que cada
# request activo reinicie el conteo de SESSION_COOKIE_AGE, así que son 30
# minutos de INACTIVIDAD (no 30 minutos fijos desde el login). Configurable
# vía variable de entorno si Administración pide otro umbral.
SESSION_COOKIE_AGE = int(os.environ.get('SESSION_COOKIE_AGE', '1800'))
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Errores visibles en producción.
#
# Por omisión, el handler de consola de Django está filtrado por
# `require_debug_true`, así que con DEBUG=False los tracebacks de un error
# 500 no llegan a ningún lado: el usuario ve "Server Error (500)" y en los
# logs de Railway no aparece absolutamente nada. Esto los manda a stderr,
# que es lo que Railway captura.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'detallado': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'consola': {
            'class': 'logging.StreamHandler',
            'stream': sys.stderr,
            'formatter': 'detallado',
        },
    },
    'loggers': {
        # Incluye el traceback completo de cualquier excepción no atrapada.
        'django.request': {'handlers': ['consola'], 'level': 'ERROR', 'propagate': False},
        'django': {'handlers': ['consola'], 'level': 'WARNING', 'propagate': False},
        # Los avisos propios (cortes omitidos, fallos de la bitácora,
        # timeouts de ConsultorioWeb) que hoy se escribían al vacío.
        'apps': {'handlers': ['consola'], 'level': 'INFO', 'propagate': False},
    },
}

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'

# Reemplaza la página "403 Forbidden" en blanco que Django muestra cuando un
# formulario se rechaza por CSRF (el caso reportado: usar "atrás" del
# navegador para volver a una pantalla vieja y reenviarla) por una página que
# explica qué pasó y ofrece un botón para reintentar. Ver
# apps/core/views.py::csrf_failure_view.
CSRF_FAILURE_VIEW = 'apps.core.views.csrf_failure_view'

# Archivos subidos por el usuario (ej. XML/PDF de CFDI de donativos).
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Integración con ConsultorioWeb (importación de nómina semanal sellada,
# apps/finanzas/integraciones/). Sin valor por defecto a propósito: si falta
# configurar la variable en Railway, la integración debe fallar de forma
# ruidosa en vez de intentar conectarse a algo adivinado.
CONSULTORIOWEB_API_URL = os.environ.get('CONSULTORIOWEB_API_URL', '')
CONSULTORIOWEB_API_KEY = os.environ.get('CONSULTORIOWEB_API_KEY', '')
# Segundos de espera por llamada. Holgado a propósito: ese servicio se
# duerme cuando no se usa y la primera llamada paga el arranque en frío
# (ya despierto contesta en menos de 5s hasta para un año de citas).
CONSULTORIOWEB_TIMEOUT = int(os.environ.get('CONSULTORIOWEB_TIMEOUT', '45'))

